// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: update_user.sql

package userMethods

import (
	"context"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET username = $1, email = $2, password = $3 WHERE id = $4
`

type UpdateUserParams struct {
	Username string
	Email    string
	Password string
	ID       int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	return err
}
